# 120bid 配置文件

# 数据库配置
MySQL:
  User: "root" # 用户名
  Password: "123456" # 密码
  Host: "localhost"
  Port: "3306"
  DB: "test" # 数据库名

# 查询参数配置
Params:
  Keywords: ["氧气"]
  Status: []
  StartDate: ""
  EndDate: ""

# 代理IP配置
ProxyIP:
  AuthKey: "*******"
  Password: "*******"